### ISSUE TITLE
User stuck at loading screen with no helpful info when player account cannot be retrieved

### ISSUE THREAD

**Issue by heyheyjp** [LearnersGuild/echo-chat#21]
Related to https://github.com/LearnersGuild/game/issues/214.

If a user's github account is authenticated and their idm user is retrieve but a player account cannot be found in the game service, the user gets stuck at the splash/loading screen. Instead, we should display an error and perhaps direct the user to contact an administrator.

**Comment by jeffreywescott** [comment]
Should be fixed now.
