### ISSUE TITLE
Increase default "member list" to 10

### ISSUE THREAD

**Issue by jeffreywescott** [LearnersGuild/echo-chat#28]
@shereefb commented on [Tue Jul 05 2016](https://github.com/LearnersGuild/learning-os-software/issues/123)

During playtesting, I used the "member list" on the channel multiple times to figure out who is part of my project/team. The "show all" link expands the list, but it's limited to 5 by default. That limit should be increased to 10. 

For teams size of 4 it's easy to miss the last person on the team. 

---

@shereefb commented on [Tue Jul 05 2016](https://github.com/LearnersGuild/learning-os-software/issues/123#issuecomment-230552608)

@tannerwelsh assigning to you for UX approval.

**Comment by tannerwelsh** [comment]
Approved!

**Comment by jeffreywescott** [comment]
Moving of of Rocket.Chat longer-term ... closing.
