### ISSUE TITLE
Change "Users" group to "Players"

### ISSUE THREAD

**Issue by jeffreywescott** [LearnersGuild/echo-chat#29]
@shereefb commented on [Tue Jul 05 2016](https://github.com/LearnersGuild/learning-os-software/issues/129)

![image](https://cloud.githubusercontent.com/assets/108545/16602924/debe1394-42cc-11e6-8b4e-c7dbb7ac1d25.png)

**Comment by jeffreywescott** [comment]
@shereefb -- I don't really agree with this change. The issue is that not every "user" in echo is a "player", but every account-holder on echo that is not a "bot" is a "user". It's worth noting that these are Rocket.Chat groups, not _our_ groups, and we're not really using them to affect our software at all.

That said, it _might_ be worth it to differentiate between players and moderators in a visual way, and we _could_ potentially use Rocket.Chat groups to serve that purpose. Is that what you're aiming at here? If we go that route, it would probably show people like this:

**@tannerwelsh** `Admins` `Users` `Moderators`

**@jeffreywescott** `Admins` `Users`

**@carlabagdonas** `Users` `Moderators`

**Comment by shereefb** [comment]
yep. nevermind.
