### ISSUE TITLE
Filter inactive project channel names from autosuggest list

### ISSUE THREAD

**Issue by heyheyjp** [LearnersGuild/echo-chat#31]
Typing `#` in rocket.chat causes a list of autosuggested channel names to appear. We're able to use this as a hack for getting autosuggest/autocomplete of project names since every project created has a channel with the same name as the project.

However, as time goes on and the number of projects (and therefore channels) increases, this list is going to grow to such a length that it'll negatively impact the user experience.

Is there a way that we can filter out channels for projects that are no longer active? For example, if we were to automatically archive a project's channel on `/cycle end`, would that cause it to be excluded from the autosuggest list?

<img width="1177" alt="screen shot 2016-07-11 at 1 27 38 pm" src="https://cloud.githubusercontent.com/assets/1890882/16745754/2b0f6524-476c-11e6-97a2-1b9577ef84e8.png">

**Comment by jeffreywescott** [comment]
Maybe we should auto-archive channels that:
- are associated with a project that has ended, **and**
- haven't had any activity in XXX weeks

**Comment by jeffreywescott** [comment]
Tracked here: https://app.clubhouse.io/learnersguild/story/409/inactive-echo-channels-should-be-automatically-archived
