### ISSUE TITLE
Fix sidebar color

### ISSUE THREAD

**Issue by heyheyjp** [LearnersGuild/echo-chat#46]
The first screenshot is dev (local). The second is in prod. The colors in dev look a lot better.

<img width="1120" alt="screen shot 2016-07-25 at 10 45 42 am" src="https://cloud.githubusercontent.com/assets/1890882/17111099/fdf90042-5254-11e6-95a2-6187d3674819.png">

<img width="1120" alt="screen shot 2016-07-25 at 10 45 52 am" src="https://cloud.githubusercontent.com/assets/1890882/17111109/05fb48fe-5255-11e6-9e33-e6592e13934c.png">

**Comment by jeffreywescott** [comment]
The dev colors are Rocket.Chat defaults. The prod colors I tried to make match the default styling of our react-toolbox stuff. It'd be great to get everything consistent and beautiful.

The native app is particularly jarring b/c the switcher bar matches their default colors but not ours and it's not configurable.

**Comment by jeffreywescott** [comment]
This will be addressed (for better or worse) when we integrate new guild branding.
