### ISSUE TITLE
Set up incoming webhook for direct messaging

### ISSUE THREAD

**Issue by heyheyjp** [LearnersGuild/echo-chat#50]
@prattsj commented on [Tue Aug 02 2016](https://github.com/LearnersGuild/game/issues/360)

Fortunately, we won't have to wade in any real Meteor/Rocket.Chat 💩 to get it done. Found sufficient (though unfortunately, undocumented) support already built into RC for sending direct messages through the API.

**Setup:**
1. Simple webhook config
   
   <img width="824" alt="screen shot 2016-08-02 at 12 06 26 am" src="https://cloud.githubusercontent.com/assets/1890882/17319931/c195555a-5845-11e6-83fa-1114e3c30387.png">
2. Simple API call
   
   <img width="888" alt="screen shot 2016-08-02 at 12 08 28 am" src="https://cloud.githubusercontent.com/assets/1890882/17319937/cf00f7a8-5845-11e6-8886-d217a2cd420a.png">
3. Et voila...direct messages
   
   <img width="831" alt="screen shot 2016-08-02 at 12 09 02 am" src="https://cloud.githubusercontent.com/assets/1890882/17319947/da4ca5b2-5845-11e6-8a4e-5690f26da05b.png">

**Comment by jeffreywescott** [comment]
I'm a bit nervous about using `#general` as the fallback for something that is primarily intended for direct messages. I think I'd rather things error-out than mistakenly post to #general. WDYT?

**Comment by heyheyjp** [comment]
Totes. See my note in the image about using something safer. I bet we can set up a private channel and feed anything that falls through to that?

**Comment by heyheyjp** [comment]
When we switch this to being handled by our custom namespaced API endpoints, I like the idea of just erroring out.

**Comment by jeffreywescott** [comment]
Ah -- I misunderstood you ... I thought you were suggesting that #general _was_ safe. Sorry.

**Comment by jeffreywescott** [comment]
FWIW, anyone with the `backoffice` role in IDM automatically gets the `admin` role in Rocket.Chat and should be able to set this up.

**Comment by heyheyjp** [comment]
Complete.

![screen shot 2016-08-05 at 11 12 13 am](https://cloud.githubusercontent.com/assets/1890882/17446301/7f5ce9ae-5afd-11e6-910d-3c2727e857dc.png)
