### ISSUE TITLE
if user changes email address in GitHub, echo sign-in will create a new user

### ISSUE THREAD

**Issue by jeffreywescott** [LearnersGuild/echo-chat#58]
Found via rocketchat-lg-sso code review w/ @bundacia ...

We should be querying on:

`services.lgSSO.lgUser.id` instead of `emails.address`

**Comment by bundacia** [comment]
So, this is interesting. Email is how we look you up when you log into idm in the first place. So if a player changes their email in GH (and removes the old one) IDM will assume they have no account at all. We could lookup by username instead, but that can be changed also. It seems like maybe we need to lookup users by their GH id?

**Comment by heyheyjp** [comment]
+1 for github ID. seems the only reliable way to go here, especially since the messaging in the UI is around authentication via github specifically.

**Comment by bundacia** [comment]
blocked by https://github.com/LearnersGuild/idm/issues/127

**Comment by bundacia** [comment]
[This branch](https://github.com/LearnersGuild/echo-chat/compare/lg-master...LearnersGuild:echo-chat-58?expand=1) should fix the issue, but it will be easier to test once idm#127 is live

**Comment by bundacia** [comment]
In practice what will happen if you change your email address is that when you try to sign in to echo it will _try_ to create a new account with the same username and fail with this error:

> [lg-sso] error signing-in using SSO on idm service Error: Username already exists. [403]

Which to the user looks the same as every other login failure.
