### ISSUE TITLE
Github username change issue

### ISSUE THREAD

**Issue by jeffreywescott** [LearnersGuild/echo-chat#59]
@harmanlearns commented on [Sat Aug 13 2016](https://github.com/LearnersGuild/los/issues/53)
### Expected vs. Actual

_What were you attempting to do? What actually happened?_
I changed my github username to match my email and website. It caused echo to have issues in terms of private groups and having the same permissions as a user in channels.

I can not see any of the previous private channels and no more gear icon next to a post in certain channels.
### Steps to Reproduce

_How can you reproduce the bug? Include as much detail as you can._
-Change github username
-try to use echo again in same channels as previous username
### Environment and Versions

_What versions of relevant external software were you using (browser, OS, etc.)?_
Chrome on Mac. 

---

@jeffreywescott commented on [Mon Aug 15 2016](https://github.com/LearnersGuild/los/issues/53#issuecomment-239785352)

Thanks for reporting this, @harmanlearns. Is this blocking you from being able to work / collaborate (trying to prioritize)?

---

@harmanlearns commented on [Mon Aug 15 2016](https://github.com/LearnersGuild/los/issues/53#issuecomment-239803503)

@Jeffrey: This is not blocking me from working right now. I can send and receive messages.

This can be fixed  when there is time available. I mainly cannot:

-react to messages
-edit messages after sending on some channels
-access private channels

Thanks!

> On Aug 15, 2016, at 4:55 AM, Jeffrey Wescott notifications@github.com wrote:
> 
> Thanks for reporting this, @harmanlearns. Is this blocking you from being able to work / collaborate (trying to prioritize)?
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.

---

@jeffreywescott commented on [Mon Aug 15 2016](https://github.com/LearnersGuild/los/issues/53#issuecomment-239804255)

Related: https://github.com/RocketChat/Rocket.Chat/issues/3545

**Comment by bundacia** [comment]
afaict we need to do this when the username changes:

``` javascript
RocketChat.callbacks.run('usernameSet')
```

(see [packages/rocketchat-ui-login/username/username.coffee](https://github.com/LearnersGuild/echo-chat/blob/84b0f07a184a804c677dae4e4657ad798caefa61/packages/rocketchat-ui-login/username/username.coffee#L47))

UPDATE: actually this doesn't look like the right thing.

**Comment by jeffreywescott** [comment]
Cool. R U gonna give it a try in dev to see if it works? We probably need an `updateUsernameIfChanged` function in `server/sso.js` ...

**Comment by bundacia** [comment]
@jeffreywescott: Working on it, just making notes here as I dig around.

**Comment by bundacia** [comment]
Looks like this is where the magic happens: [packages/rocketchat-lib/server/functions/setUsername.coffee](https://github.com/LearnersGuild/echo-chat/blob/84b0f07a184a804c677dae4e4657ad798caefa61/packages/rocketchat-lib/server/functions/setUsername.coffee#L33-55)

**Comment by bundacia** [comment]
This code fix still leaves @harmanlearns' data messed up, so I created a chore to get that fixed: #61
