### ISSUE TITLE
Fixup @harmanlearns' username data

### ISSUE THREAD

**Issue by bundacia** [LearnersGuild/echo-chat#61]
See #59 

One option here would be to just temporarily re-enable the ability for users to change their username and then change @harmanlearns username back to the old value and then back to the new one. That should trigger all the right cleanup.

**Comment by harmanTheCarMan** [comment]
@Trevor: 

That sounds like a cool solution :) Sorry to create more issues. I just wanted my online branding to match my email and website of the same name lol. I waited to change github username as the last thing thinking this would cause some issues.

**Comment by bundacia** [comment]
@harmanlearns no worries! I've actually been wanting to change my github username for a while and have put it off because I didn't know if it would cause problems. So I'm glad this came up so we could find the problems and fix them! As soon as we get everything sorted out I'll probably go ahead and change my username as well.

**Comment by jeffreywescott** [comment]
I'm pretty sure this got resolved, right @bundacia / @harmanlearns? Please re-open if not.

**Comment by harmanTheCarMan** [comment]
yes! changing back to old username then switching to new one allowed and logging in and out made sure it all worked great :)
