### ISSUE TITLE
Echo fails to load on iOS rocket.chat

### ISSUE THREAD

**Issue by EthanJStark** [LearnersGuild/echo-chat#74]
This week, my iOS Rocket.Chat began hanging on launch, on the red+white rocket.chat logo. Notifications continued to work until I deleted the app and reinstalled it. Now, when attempting to connect, it makes it past "validating server" and hangs with the spinner on "downloading files"

I know that supporting multiple platforms may be tricky, but it was mighty useful to have those notifications on my phone.  Thanks, team--let me know if you need any more info from me.

My Rocket.Chat version: 2.4.0

**Comment by jeffreywescott** [comment]
This is being tracked here: https://github.com/LearnersGuild/los/issues/97
